function mov=display_skeleton_data(V0,skeleton_annotation, frame_num, h)
% mov=display_skeleton_data(V0,skeleton_annotation, frame_num, h)
% Function to display skeleton annotations generated with the pose
% estimation code from the ETH research group.  The code generates a video with 
% annotated frames and shows the time series generated by tracking
% different body parts across the whole video. Pose estimation code is
% available from:
% http://www.vision.ee.ethz.ch/~calvin/articulated_human_pose_estimation_code/
%
% V0                    -- is the video to be displayed
% skeleton_annotation   -- is a matrix with skeleton annotations for each
%                          frame in V0. It is a matrix of size (number of
%                          frames * 6, 10). Rows corresponds to the
%                          information of a body part in a particular fram one 
%                          annotation point and columns are properties as
%                          follows:   
%                       Frame No. | Body part ID | X | Y | Width | Height |x1 | y1 | x2| y2|
%                       Where body parts are represented as follows: 
%                           Body part ID: 	1. Torso
%                                           2. Right upper arm 
%                                           3. Left upper arm 
%                                           4. Right lower arm
%                                           5. Left lower arm 
%                                           6. Head
%
%                       | X | Y | Width | Height |:	Are the x, y width and height for the bounding box containing the body part. 
%                       | x1 | y1 | x2| y2|:		Are the x1,y1, x2,y2 coordinates for the sticks associated with the skeleton. 		
%
% Returns:
% mov -- a movie with the annotations overlayed

if nargin<3,
    frame_list=1:length(V0);
else
    frame_list=frame_num; 
end
if nargin<4
	h=figure; set(gcf, 'Name', 'Skeleton annotations with the ETHs code');
else
    figure(h);
end
hold on;

col='rgbymck';

for i=frame_list
        IM=V0(i).cdata;
        clf;
        imagesc(IM); 
        %%%%%%% Show the annotations obtained with the pose estimation code       
        annot_idx=find(skeleton_annotation(:, 1)==i);
        for j=1:length(annot_idx)
            k=annot_idx(j);
            box0=skeleton_annotation(k, 3:6);
            rectangle('Position', box0, 'EdgeColor', col(j));                        
            box1=skeleton_annotation(k, 7:10);
                    line([box1(1),box1(3)],[box1(2),box1(4)],'Linewidth',3,'Color',col(j));
        end   
        mov(i)=getframe(h);
end

% Make a full movie, if we did not specify just one frame
if length(frame_list)==1
    return
end

%mov=immovie(movf);
% % % % Display a movie showing the detected body parts
%implay(mov,10);


% % % % Get the centers of the bounding boxes for x and y axes
centersx=[skeleton_annotation(:,3)+round(skeleton_annotation(:,5)./2)];
centersy=[skeleton_annotation(:,4)+round(skeleton_annotation(:,6)./2)];        

% % % % plot the x and y time series generated by tracking the centers
% % % % across the frames of the video

bps={'Torso','R-UpperArm','L-UpperArm','R-LowerArm','L-LowerArm','Head'};
figure; set(gcf, 'Name', 'Time series from the body parts - ETH code'); gcf; hold on;
r=repmat(1:6,1,size(skeleton_annotation,1)./6);
for i=1:6,   
    ofin=find(r==i);
    subplot(2,3,i);
    plot(centersx(ofin),col(i),'LineWidth',2); gcf; hold on;
    plot(centersy(ofin),[':' col(i)],'LineWidth',2); title(bps{i});
    legend('X-axis','Y-axis');
end
set(gcf,'Color','w');
