function mov=display_boxes_Deva(V0, bsx, frame_num, h)
% mov=display_boxes_Deva(V0, bsx, frame_num, h)
% Function to display body part annotations generated with the pose
% estimation code from Deva Ramanan. The code generates a video with 
% annotated frames and shows the time series generated by tracking
% different body parts across the whole video. 
%
% Deva Ramanan's code is publicly available from
% http://phoenix.ics.uci.edu/software/pose/
%
% V0                    -- is the video to be displayed
% bsx:  Is a 3D matrix with dimension (n x m x k), where k is the number of 
%       frames in V0, n=18 is the number of boxes that are obtained, where
%       each box is associated to a articulation point in the body and m is the 
%       number of measurments that are stored for each frame and for each body
%       part. The stored measurements are the following as follows:
%           1 - x1 position of the box
%           2 - y1 position of the box
%           3 - x2 position of the box
%           4 - y2 position of the box
%           5 - x position of the center of the box
%           6 - y position of the center of the box
%           7 - area of the box
% Returns:
% mov -- a movie with the annotations overlayed

if nargin<3,
    frame_list=1:length(V0);
else
    frame_list=frame_num; 
end
if nargin<4
	h=figure; set(gcf, 'Name', 'Skeleton annotations with the ETHs code');
else
    figure(h);
end
hold on;

partcolor= {'g','g','y','m','m','m','m','y','y','y','r','r','r','r','y','c','c','c','c','y','y','y','b','b','b','b'};
numparts=size(bsx,1);
xpos=[];
ypos=[];
for ii=frame_list
    IM=V0(ii).cdata;
    clf; imagesc(IM); axis image; axis off; drawnow;
    gcf; hold on;        
    boxes=bsx(:,:,ii);
    if ~isempty(boxes)
      for i = 1:numparts,
        line([boxes(i,1) boxes(i,1) boxes(i,3) boxes(i,3) boxes(i,1)]',[boxes(i,2) boxes(i,4) boxes(i,4) boxes(i,2) boxes(i,2)]','color',partcolor{i},'linewidth',2);
        gcf; hold on;
        plot(boxes(i,1)+((boxes(i,3)-boxes(i,1))./2),boxes(i,2)+((boxes(i,4)-boxes(i,2))./2),['o' partcolor{i}]);               
      end
      
      xpos=[xpos,boxes(:,5)];
      ypos=[ypos,boxes(:,6)];
    end
    drawnow;          
    mov(ii)=getframe(h);
    %saveas(gcf, 'tempoutput', 'jpeg');
    %II=imread('tempoutput.jpg');
    %V(:,:,:,ii)=imresize(II,0.5);        
    %close all;
end  %%% end ii

%mov=immovie(V);
% % % % Display a movie showing the detected body parts
%implay(mov,10);

if length(frame_list)>1
    figure; set(gcf, 'Name', 'Time series from the body parts - Deva Ramanans code'); gcf; hold on;
    for i=1:18,   
        %ofin=find(r==i);
        subplot(3,6,i);
        plot(xpos(i,:),partcolor{i},'LineWidth',2); gcf; hold on;
        plot(ypos(i,:),[':' partcolor{i}],'LineWidth',2); title(['Level: ' num2str(i)]);
        legend('X-axis','Y-axis');
    end
    set(gcf,'Color','w');
end

end
