function [label, dict] = gesturelabel()
label = {'ShakeHand', 'WaveHello', 'SwipeRight', 'SwipeLeft', ...
  'CirclePalmRotation', 'CirclePalmDown', 'TakeFromScreen', ...
  'PushToScreen', 'PalmDownRotation', 'PalmUpRotation', 'PreStroke', ... 
  'PostStroke', 'Rest'};

dict = containers.Map(label, 1 : length(label));
end